window.TELEGRAM_BOT_TOKEN = "8905574743:AAHWFbMJHflXvP07h2gSd__PpZ6ut_ZVld0";
window.AI_KEY = "";

window.firebaseConfig = {
  apiKey: "AIzaSyA5nEN5QiDwSxIShJdwmpbEoHKkEkNLIxM",
  authDomain: "hub-ingegneria.firebaseapp.com",
  projectId: "hub-ingegneria",
  storageBucket: "hub-ingegneria.firebasestorage.app",
  messagingSenderId: "58933321877",
  appId: "1:58933321877:web:1e3f4630edc9f192865077"
};

window.i18n = {
  it: {
    hubName:"Engineering Cloud Hub", search:"Cerca", calcTitle:"Calcolatrice", newsTitle:"Notizie",
    newsTabAll:"Tutte", newsTabTech:"Tecnologia", newsTabEconomy:"Economia", newsLoading:"Caricamento notizie...",
    chatTitle:"Assistente AI", clear:"Pulisci", chatWelcome:"Ciao! Sono l'assistente dell'Engineering Cloud Hub. Come posso aiutarti oggi?", send:"Invia",
    userTitle:"Gestione Utenti", userLoading:"Caricamento utenti...",
    mtbfHours:"Ore di funzionamento totali", mtbfFailures:"Numero guasti", calcMtbfBtn:"Calcola MTBF",
    subscribersTitle:"Iscritti Newsletter", subscribersLoading:"Caricamento iscritti...",
    newsHistoryTitle:"Storico Notizie", newsHistoryLoading:"Caricamento storico...",
    teamTitle:"Team", addMember:"Aggiungi", teamLoading:"Caricamento membri team...",
    statsTitle:"Statistiche Cloud",
    dashboardTitle:"Dashboard", dashboardSubtitle:"Seleziona un'operazione per iniziare",
    dashExcel:"Excel", dashDoc:"Documenti", dashNotes:"Note", dashArchive:"Archivio", dashHistory:"Registro Attività",
    excelModalTitle:"Carica Excel", excelFolderLabel:"Cartella", branchLabel:"Categoria",
    selectFolder:"Seleziona cartella", selectBranch:"Seleziona categoria",
    newFolderName:"Nome nuova cartella", folderColor:"Colore", createFolder:"Crea",
    excelNoteLabel:"Nota (opzionale)", dropExcel:"Trascina qui il file Excel o clicca per selezionare", uploadExcel:"Carica Excel",
    docModalTitle:"Carica Documento", docFolderLabel:"Cartella", docTitleLabel:"Titolo documento",
    docContentLabel:"Contenuto (opzionale)", dropDoc:"Trascina qui il file o clicca per selezionare (PDF, DOC, TXT, DWG, DXF)", uploadDoc:"Carica Documento",
    notesModalTitle:"Note Rapide", newNoteLabel:"Nuova nota", addNote:"Aggiungi Nota", sidebarExcelStat:"Excel", sidebarDocStat:"Docs", sidebarNotesStat:"Note",
    archiveModalTitle:"Archivio", allFolders:"Tutte le cartelle",
    downloadSelected:"Scarica selezionati", deleteSelected:"Elimina selezionati",
    selectAll:"Seleziona tutti", fileName:"Nome File", fileSize:"Dimensione", uploadDate:"Data", uploadedBy:"Categoria", editCategory:"Modifica",
    historyModalTitle:"Registro Attività", message:"Messaggio", date:"Data", user:"Utente",
    sidebarTitle:"Pannello Cloud", management:"Gestione", manageUsers:"Gestione Utenti",
    newsletterSubscribers:"Iscritti Newsletter", newsHistory:"Storico Notizie",
    cloudStats:"Statistiche Cloud", hubInfo:"Info Hub", info:"Informazioni",
    version:"Versione:", uptime:"Attivo da:", lastUpdate:"Ultimo aggiornamento:", localTime:"Ora locale:",
    footerCopyright:"\u00a9 2025 Engineering Cloud Hub", footerRights:"Tutti i diritti riservati.",
    openPanel:"Apri Pannello", assistant:"Assistente",
    loginUser:"Nome Utente", loginPass:"Password", rememberMe:"Ricordami", loginBtn:"Accedi",
    loginError:"\u26a0\ufe0f Credenziali errate. Riprova.", loginSubtitle:"Accedi per continuare",
    aiPlaceholder:"Interroga l'archivio dei file...", dateLabel:"Data", timeLabel:"Ora", close:"Chiudi",
    calcMat:"Materiale", calcShape:"Geometria Sezione", calcLen:"Lunghezza Barra (mm)", calcBtn:"Esegui Calcolo", calcRes:"Massa Totale:",
    newsPlaceholder:"Scrivi un update logistico o di bacheca...", newsBtn:"Invia News",
    sidebarSubscribe:"Attiva", sidebarUnsubscribe:"Disattiva",
    manageCategories:"Gestione Categorie", myAccount:"Il Mio Account", registration:"Registrazione", createAccount:"Crea un Account", calculators:"Calcolatori",
    privateSpace:"Spazio Privato", requestPrivateSpace:"Richiedi Spazio Privato", privateRequests:"Richieste Spazio Privato", privateActive:"Spazio privato attivo",
    deleteMyAccount:"Elimina il mio account",
    titleCalc:"Calcolatrice", titleMtbf:"MTBF", titleNews:"Notizie", titleTheme:"Tema", titleMenu:"Menu",
    calcMtbfBtn2:"Calcola MTBF",
    mtbfResultLabel:"MTBF", mtbfUnit:"ore tra un guasto e l'altro",
    lambdaLabel:"\u03bb (Failure Rate)", lambdaUnit:"guasti/ora",
    mtbfYearsUnit:"su 8760 h/anno",
    reliabilityTitle:"Affidabilit\u00e0 R(t) = e\u207b\u03bb\u1d57",
    after24h:"Dopo 24h:", after168h:"Dopo 168h (1 sett.):", after720h:"Dopo 720h (1 mese):", after8760h:"Dopo 8760h (1 anno):",
    showTechDetails:"Mostra dettagli tecnici",
    calcDimLabel:"Diametro (mm)", calcDim2Label:"Altezza (mm)",
    mtbfDesc:"<b>MTBF</b> (Mean Time Between Failures) &egrave; l'intervallo medio tra due guasti consecutivi. Si calcola come:<br><b>MTBF = Ore totali / Numero Guasti</b>",
    mtbfYearsLabel:"MTBF (anni)",
    mtbfDetails:"<p><b>MTBF</b> = T / n = ore totali / guasti</p><p><b>&lambda;</b> (Failure Rate) = 1 / MTBF = n / T</p><p><b>R(t)</b> = e<sup>-&lambda;t</sup> (affidabilit&agrave; esponenziale)</p><p><b>MTTR</b> = Tempo medio di riparazione (da inserire separatamente)</p><p><b>Disponibilit&agrave;</b> A = MTBF / (MTBF + MTTR)</p><p class='text-gray-400 italic mt-1'>I valori sono indicativi e presuppongono una distribuzione esponenziale dei guasti (modello &agrave; tasso costante).</p>"
  },
  en: {
    hubName:"Engineering Cloud Hub", search:"Search", calcTitle:"Calculator", newsTitle:"News",
    newsTabAll:"All", newsTabTech:"Technology", newsTabEconomy:"Economy", newsLoading:"Loading news...",
    chatTitle:"AI Assistant", clear:"Clear", chatWelcome:"Hi! I'm the Engineering Cloud Hub assistant. How can I help you today?", send:"Send",
    userTitle:"User Management", userLoading:"Loading users...",
    mtbfHours:"Total operating hours", mtbfFailures:"Number of failures", calcMtbfBtn:"Calculate MTBF",
    subscribersTitle:"Newsletter Subscribers", subscribersLoading:"Loading subscribers...",
    newsHistoryTitle:"News History", newsHistoryLoading:"Loading history...",
    teamTitle:"Team", addMember:"Add", teamLoading:"Loading team members...",
    statsTitle:"Cloud Statistics",
    dashboardTitle:"Dashboard", dashboardSubtitle:"Select an operation to start",
    dashExcel:"Excel", dashDoc:"Documents", dashNotes:"Notes", dashArchive:"Archive", dashHistory:"Activity Log",
    excelModalTitle:"Upload Excel", excelFolderLabel:"Folder", branchLabel:"Category",
    selectFolder:"Select folder", selectBranch:"Select category",
    newFolderName:"New folder name", folderColor:"Color", createFolder:"Create",
    excelNoteLabel:"Note (optional)", dropExcel:"Drag Excel file here or click to select", uploadExcel:"Upload Excel",
    docModalTitle:"Upload Document", docFolderLabel:"Folder", docTitleLabel:"Document title",
    docContentLabel:"Content (optional)", dropDoc:"Drag file here or click to select (PDF, DOC, TXT, DWG, DXF)", uploadDoc:"Upload Document",
    notesModalTitle:"Quick Notes", newNoteLabel:"New note", addNote:"Add Note", sidebarExcelStat:"Excel", sidebarDocStat:"Docs", sidebarNotesStat:"Notes",
    archiveModalTitle:"Archive", allFolders:"All folders",
    downloadSelected:"Download selected", deleteSelected:"Delete selected",
    selectAll:"Select all", fileName:"File Name", fileSize:"Size", uploadDate:"Date", uploadedBy:"Category", editCategory:"Edit",
    historyModalTitle:"Activity Log", message:"Message", date:"Date", user:"User",
    sidebarTitle:"Cloud Panel", management:"Management", manageUsers:"User Management",
    newsletterSubscribers:"Newsletter Subscribers", newsHistory:"News History",
    cloudStats:"Cloud Statistics", hubInfo:"Hub Info", info:"Information",
    version:"Version:", uptime:"Active since:", lastUpdate:"Last update:", localTime:"Local time:",
    footerCopyright:"\u00a9 2025 Engineering Cloud Hub", footerRights:"All rights reserved.",
    openPanel:"Open Panel", assistant:"Assistant",
    loginUser:"Username", loginPass:"Password", rememberMe:"Remember me", loginBtn:"Sign In",
    loginError:"\u26a0\ufe0f Invalid credentials. Try again.", loginSubtitle:"Sign in to continue",
    aiPlaceholder:"Search the file archive...", dateLabel:"Date", timeLabel:"Time", close:"Close",
    calcMat:"Material", calcShape:"Section Geometry", calcLen:"Bar Length (mm)", calcBtn:"Calculate", calcRes:"Total Mass:",
    newsPlaceholder:"Write a logistic or board update...", newsBtn:"Send News",
    sidebarSubscribe:"Subscribe", sidebarUnsubscribe:"Unsubscribe",
    manageCategories:"Category Management", myAccount:"My Account", registration:"Registration", createAccount:"Create an Account", calculators:"Calculators",
    privateSpace:"Private Space", requestPrivateSpace:"Request Private Space", privateRequests:"Private Space Requests", privateActive:"Private space active",
    deleteMyAccount:"Delete my account",
    titleCalc:"Calculator", titleMtbf:"MTBF", titleNews:"News", titleTheme:"Theme", titleMenu:"Menu",
    calcMtbfBtn2:"Calculate MTBF",
    mtbfResultLabel:"MTBF", mtbfUnit:"hours between failures",
    lambdaLabel:"\u03bb (Failure Rate)", lambdaUnit:"failures/hour",
    mtbfYearsUnit:"per 8760 h/year",
    reliabilityTitle:"Reliability R(t) = e\u207b\u03bb\u1d57",
    after24h:"After 24h:", after168h:"After 168h (1 week):", after720h:"After 720h (1 month):", after8760h:"After 8760h (1 year):",
    showTechDetails:"Show technical details",
    calcDimLabel:"Diameter (mm)", calcDim2Label:"Height (mm)",
    mtbfDesc:"<b>MTBF</b> (Mean Time Between Failures) is the average time between two consecutive failures. Calculated as:<br><b>MTBF = Total hours / Number of Failures</b>",
    mtbfYearsLabel:"MTBF (years)",
    mtbfDetails:"<p><b>MTBF</b> = T / n = total hours / failures</p><p><b>&lambda;</b> (Failure Rate) = 1 / MTBF = n / T</p><p><b>R(t)</b> = e<sup>-&lambda;t</sup> (exponential reliability)</p><p><b>MTTR</b> = Mean Time To Repair (insert separately)</p><p><b>Availability</b> A = MTBF / (MTBF + MTTR)</p><p class='text-gray-400 italic mt-1'>Values are indicative and assume an exponential failure distribution (constant rate model).</p>"
  }
};
